### ISSUE TITLE
Speed Very Slow

### ISSUE THREAD

**Issue by FungluiKoo** [DeepTrial/Twitter-Spider#1]
Hi there, thank you for sharing your great work!
I'm using your repo to crawl some twitter accounts with interface.scrap_between_date() method. It turns out to be very slow (about 300 tweets per hour). Looking at the terminal, it seems that the program will stop for a while after crawling several (about 5) tweets.

**Comment by DeepTrial** [comment]
That is true, I use sleep to get it slower because some say that twitter may block your ip/account if you crawl too much data in a short time.

you can speed up by decrease the seconds in sleep but I must tell you that it is risky to do that.

**Comment by FungluiKoo** [comment]
The speed issue has been solved. The program can now crawl at 1~2 tweet per second, which is acceptable while not being blocked by Twitter.
https://github.com/DeepTrial/Twitter-Spider/commit/043e4ed949bafd8708e2a55aa1ae7b885d73dd59
