### ISSUE TITLE
Tweets not Strictly in Chronicle Orders

### ISSUE THREAD

**Issue by FungluiKoo** [DeepTrial/Twitter-Spider#2]
Hi there, I'm using `interface.scrap_between_date()` method, and find that the tweets gathered are not strictly in chronicle orders. For example:

INFO:parsing_engine.log:Found tweet made at 2021-03-03T01:53:56.000Z
INFO:parsing_engine.log:Found tweet made at 2021-03-04T16:49:40.000Z
INFO:parsing_engine.log:Found tweet made at 2021-03-02T22:54:26.000Z
INFO:parsing_engine.log:Found tweet made at 2021-03-04T01:11:08.000Z
INFO:parsing_engine.log:Found tweet made at 2021-03-02T13:30:56.000Z
INFO:parsing_engine.log:Found tweet made at 2021-03-03T15:21:58.000Z
INFO:parsing_engine.log:Found tweet made at 2021-03-04T17:06:25.000Z
INFO:parsing_engine.log:Found tweet made at 2021-03-02T23:31:32.000Z
INFO:parsing_engine.log:Found tweet made at 2021-03-02T15:16:34.000Z

The entries in the CSV file has the same order as in logs above.

**Comment by DeepTrial** [comment]
I did not notice this problem, thanks. I will check it carefully.

**Comment by FungluiKoo** [comment]
Looking at the codes, I find that `scrap_between_date()` in `interface.py` would search for only three days at one time. Maybe this is not necessary. If we just search the whole period at once, we would get the tweets in reverse chronological order (as it has set `f=liv` which means latest).

By the way, I made some modifications so that we could make life easier with command lines. Please kindly check it and accept my pull request :)

**Comment by FungluiKoo** [comment]
I modified the codes a little bit, and now it can generate outputs in reverse chronicle order (most recent to least recent). I sent a pull request. Please kindly check it up :)
